# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTextEdit

class PlaceholderTextEdit(QTextEdit):
    def __init__(self, placeholder, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.placeholder_text = placeholder
        self.placeholder_visible = True

        # Poner el placeholder al iniciar
        self.setPlainText(self.placeholder_text)
        self.setStyleSheet("QTextEdit { color: #a9a9a9; }")
        self.setAlignment(QtCore.Qt.AlignLeft)

    def focusInEvent(self, event):
        # Al ganar foco por primera vez, borrar el placeholder
        if self.placeholder_visible:
            self.clear()
            self.setStyleSheet("QTextEdit { color: black; }")
            self.placeholder_visible = False
        super().focusInEvent(event)

    def focusOutEvent(self, event):
        # Si pierde foco y está vacío, volver a mostrar el placeholder
        if not self.toPlainText().strip():
            self.setPlainText(self.placeholder_text)
            self.setStyleSheet("QTextEdit { color: #a9a9a9; }")
            self.setAlignment(QtCore.Qt.AlignLeft)
            self.placeholder_visible = True
        super().focusOutEvent(event)


class Ui_ReproductorDeTextos(object):
    def setupUi(self, ReproductorDeTextos):
        ReproductorDeTextos.setObjectName("ReproductorDeTextos")
        ReproductorDeTextos.resize(638, 414)
        ReproductorDeTextos.setFocusPolicy(QtCore.Qt.ClickFocus)

        # El widget central
        self.centralwidget = QtWidgets.QWidget(ReproductorDeTextos)
        self.centralwidget.setObjectName("centralwidget")
        ReproductorDeTextos.setCentralWidget(self.centralwidget)

        # Crear el layout principal y asignarlo al centralwidget
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")

        #Crear layout horizontal para los botones
        self.buttonLayout = QtWidgets.QHBoxLayout()
        #Agregar layout al layout ppal
        self.gridLayout.addLayout(self.buttonLayout,2,0,1,1)



        # Campo de texto
        self.textEdit = PlaceholderTextEdit('Escriba su texto aquí...',self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 1)


        
        # Botón reproducir
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.buttonLayout.addWidget(self.pushButton)

        # Botón para pausar
        self.pushButton_pausa = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton_pausa")
        self.buttonLayout.addWidget(self.pushButton_pausa)

        # Botón seleccionar archivo
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_3.setObjectName("pushButton_3")
        self.buttonLayout.addWidget(self.pushButton_3)

       

    # Establecer que todos los botones crezcan por igual
        self.buttonLayout.setStretch(0, 1)  # Reproducir
        self.buttonLayout.setStretch(1, 1)  # Pausar
        self.buttonLayout.setStretch(2, 1)  # Seleccionar Archivo

    #Añadir iconos
        self.pushButton.setIcon(QtGui.QIcon("icons/play.svg"))
        self.pushButton_pausa.setIcon(QtGui.QIcon("icons/pause.svg"))
        self.pushButton_3.setIcon(QtGui.QIcon("icons/folder-plus.svg"))

        # Status bar y toolbar
        self.statusbar = QtWidgets.QStatusBar(ReproductorDeTextos)
        self.statusbar.setObjectName("statusbar")
        ReproductorDeTextos.setStatusBar(self.statusbar)

        self.toolBar = QtWidgets.QToolBar(ReproductorDeTextos)
        self.toolBar.setObjectName("toolBar")
        ReproductorDeTextos.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(ReproductorDeTextos)
        QtCore.QMetaObject.connectSlotsByName(ReproductorDeTextos)

    def retranslateUi(self, ReproductorDeTextos):
        _translate = QtCore.QCoreApplication.translate
        ReproductorDeTextos.setWindowTitle(_translate("ReproductorDeTextos", "Reproductor de Texto"))
        self.pushButton.setText(_translate("ReproductorDeTextos", "Reproducir"))
        self.pushButton_3.setText(_translate("ReproductorDeTextos", "Seleccionar Archivo"))
        self.pushButton_pausa.setText(_translate("ReproductorDeTextos", "Pausar"))
        self.toolBar.setWindowTitle(_translate("ReproductorDeTextos", "toolBar"))

